version: "3.7"

services:
  app:
    image: node:12
    volumes: 
      - .:/var/app
    working_dir: /var/app
    env_file: .env
    command: tail -f /dev/null
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    links:
      - mongo
    depends_on:
      - mongo

  mongo:
    image: mongo:4.2
    restart: "unless-stopped"
    working_dir: /var/mongo
    volumes: 
      - ./db:/var/db/mongo
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
      MONGO_INITDB_DATABASE: appdata

